### ISSUE TITLE
Missing utils module in docker image

### ISSUE THREAD

**Issue by zeromage** [vector-im/matrix-content-scanner-python#40]
Without setting

ENV PYTHONPATH=/

the docker image is missing the matrix_content_scanner.utils module.
"ModuleNotFoundError: No module named 'matrix_content_scanner.utils'"

Reproduce:
cp docker/Dockerfile .
podman build -t mcs .
podman run -d mcs
podman logs [container.id]

**Comment by dklimpel** [comment]
If I am run `matrixdotorg/matrix-content-scanner:latest`, I am get
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.9/site-packages/matrix_content_scanner/mcs.py", line 23, in <module>
    from matrix_content_scanner.config import MatrixContentScannerConfig
  File "/usr/local/lib/python3.9/site-packages/matrix_content_scanner/config.py", line 20, in <module>
    from matrix_content_scanner.utils.errors import ConfigError
ModuleNotFoundError: No module named 'matrix_content_scanner.utils'
```

**Comment by dklimpel** [comment]
I also did an installation today in a virtual environment with `pip install`. It worked without any problems.

**Comment by dklimpel** [comment]
It is fixed for me in `vectorim/matrix-content-scanner:v1.0.3`.

**Comment by babolivier** [comment]
Apologies, there was a packaging issue. This was fixed in https://github.com/vector-im/matrix-content-scanner-python/commit/b497bf03be711cd20ff61fea7c4044c9c98d6c4e, which was released in v1.0.3, as @dklimpel mentioned.

**Comment by clokep** [comment]
Sounds like this can be closed then?

**Comment by babolivier** [comment]
Indeed, thanks @clokep!

**Comment by zeromage** [comment]
The fix is working for us. Thanks.
