### ISSUE TITLE
Improve Return Status Codes

### ISSUE THREAD

**Issue by yncyrydybyl** [vector-im/matrix-content-scanner-python#46]
**Describe the bug**
Right now there is a blocking message in the client, if the media file everything else than clean. So the client show the message “blocking” if the media file IS NOT CLEAN. Even in the cases

* … the MCS scanner is not working anymore (media repo not available, msc service down, …)
* … the media file could not be scanned (any reason)
* … the media file could not be found => media retention deleted the media file (correctly, works as designed/configured)

In case the media retention deleted the media file correctly, we noticed an HTTP 502 Bad Gateway error.

```
{
    "reason": "MCS_MEDIA_REQUEST_FAILED",

    "info": "File not found"
}
```

https://github.com/vector-im/matrix-content-scanner-python/blob/8e83040d41339218e03ea65a30c64cbcb8e0d2f5/src/matrix_content_scanner/scanner/file_downloader.py#L89-L95

**Expected behavior**
Wouldn’t it be better to present a status code “404 not found error” instead the “502 bad gateway”?

Then we can differentiate based on status code between an successful scan an a scan where the media content is no longer available (failed scan failed – not possible)

**Comment by anoadragon453** [comment]
I don't have any particular historic knowledge of this codebase, but taking a fresh look...

In the [API documentation](https://github.com/vector-im/matrix-content-scanner-python/blob/main/docs/api.md#error-codes), a 404 with `M_NOT_FOUND` is defined as the client approaching the Matrix Content Scanner with an incorrect HTTP Method + Path combination. However, `M_NOT_FOUND` does not appear to actually be returned by the proxy in this case, or at all (it doesn't appear in the codebase outside of [the definition](https://github.com/vector-im/matrix-content-scanner-python/blob/8e83040d41339218e03ea65a30c64cbcb8e0d2f5/src/matrix_content_scanner/utils/constants.py#L21)).

```
➜ curl -v http://127.0.0.1:8080/_matrix/measdhjkashkddas
* processing: http://127.0.0.1:8080/_matrix/measdhjkashkddas
*   Trying 127.0.0.1:8080...
* Connected to 127.0.0.1 (127.0.0.1) port 8080
> GET /_matrix/measdhjkashkddas HTTP/1.1
> Host: 127.0.0.1:8080
> User-Agent: curl/8.2.1
> Accept: */*
>
< HTTP/1.1 404 Not Found
< Content-Type: text/plain; charset=utf-8
< Content-Length: 14
< Date: Tue, 19 Sep 2023 09:56:02 GMT
< Server: Python/3.9 aiohttp/3.8.3
<
* Connection #0 to host 127.0.0.1 left intact
404: Not Found% 
```

I vote we update [the API](https://github.com/vector-im/matrix-content-scanner-python/blob/main/docs/api.md#error-codes) to make the 404 semantics the same as Synapse: on attempting an unknown HTTP Method + Path, return `404 M_UNRECOGNIZED`. And as the issue suggests, in the case of media not being found, only then return `404 M_NOT_FOUND`.

cc @giomfo who has been a consumer of this API in the past to check that this would not break any existing client implementations.

**Comment by giomfo** [comment]
I read and approve the suggested change which makes sense

**Comment by DMRobertson** [comment]
I think the actual request here is specifically that we return an appropriate 404 error when the upstream homeserver tells us a piece of media is not found, and in particular that this should work when media has been deleted due to retention.

Making the application return matrix error codes across the board is nice to have, but separate.

**Comment by DMRobertson** [comment]
> I vote we update [the API](https://github.com/vector-im/matrix-content-scanner-python/blob/main/docs/api.md?rgh-link-date=2023-09-19T09%3A59%3A28Z#error-codes) to make the 404 semantics the same as Synapse: on attempting an unknown HTTP Method + Path, return `404 M_UNRECOGNIZED`. And as the issue suggests, in the case of media not being found, only then return `404 M_NOT_FOUND`.

This sort of thing is covered by https://github.com/vector-im/matrix-content-scanner-python/issues/43.
